name: Python Aiogram Bot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo yuklash
        uses: actions/checkout@v4

      - name: Python o‘rnatish
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Kutubxonalarni o‘rnatish
        run: |
          pip install -r requirements.txt

      - name: Botni tekshirish (syntax)
        run: |
          python main.py
